mitarbeiter:
  - name: Jozef
    telegram_id: 724906623
    abteilung: Wartung
  - name: Instand.
    telegram_id: 1889729647
    abteilung: Wartung
  - name: Zoli
    telegram_id: 6964409866
    abteilung: Wartung
